
((digest . "bcdfe282af884197e479291359762b33") (undo-list nil ("* 10/3


** 2.5	DumpReader-DumpWriter結合テスト 


$ ../../build/PC/gtest/dumper/test.exe --gtest_filter=DumpCombination*

```
$ ../../build/PC/gtest/dumper/test.exe --gtest_filter=DumpCombination*
Note: Google Test filter = DumpCombination*
[==========] Running 90 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 90 tests from DumpCombination_Test/DumpCombinationTest
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/0
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/0 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/1
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/1 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/2
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/2 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/3
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/3 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/4
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/4 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/5
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/5 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/6
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/6 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/7
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/7 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/8
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/8 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/9
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/9 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/10
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/10 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/11
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/11 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/12
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/12 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/13
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/13 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/14
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/14 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/15
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/15 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/16
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/16 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/17
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/17 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/18
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/18 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/19
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/19 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/20
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/20 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/21
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/21 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/22
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/22 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/23
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/23 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/24
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/24 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/25
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/25 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/26
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/26 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/27
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/27 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/28
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/28 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/29
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/29 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/30
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/30 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/31
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/31 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/32
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/32 (1 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/33
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/33 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/34
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/34 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/35
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/35 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/36
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/36 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/37
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/37 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/38
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/38 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/39
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/39 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/40
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/40 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/41
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/41 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/42
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/42 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/43
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/43 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.HeaderTest/44
[       OK ] DumpCombination_Test/DumpCombinationTest.HeaderTest/44 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/0
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/0 (3 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/1
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/1 (12 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/2
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/2 (0 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/3
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/3 (3 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/4
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/4 (14 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/5
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/5 (10 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/6
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/6 (7 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/7
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/7 (7 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/8
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/8 (16 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/9
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/9 (7 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/10
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/10 (7 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/11
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/11 (9 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/12
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/12 (13 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/13
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/13 (20 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/14
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/14 (34 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/15
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/15 (26 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/16
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/16 (27 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/17
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/17 (19 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/18
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/18 (26 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/19
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/19 (15 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/20
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/20 (18 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/21
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/21 (11 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/22
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/22 (27 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/23
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/23 (17 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/24
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/24 (19 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/25
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/25 (15 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/26
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/26 (12 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/27
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/27 (21 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/28
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/28 (17 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/29
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/29 (40 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/30
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/30 (29 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/31
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/31 (24 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/32
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/32 (28 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/33
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/33 (18 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/34
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/34 (22 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/35
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/35 (15 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/36
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/36 (15 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/37
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/37 (12 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/38
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/38 (23 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/39
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/39 (18 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/40
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/40 (16 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/41
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/41 (19 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/42
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/42 (12 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/43
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/43 (28 ms)
[ RUN      ] DumpCombination_Test/DumpCombinationTest.DataTest/44
[       OK ] DumpCombination_Test/DumpCombinationTest.DataTest/44 (17 ms)
[----------] 90 tests from DumpCombination_Test/DumpCombinationTest (774 ms total)

[----------] Global test environment tear-down
[==========] 90 tests from 1 test case ran. (4422 ms total)
[  PASSED  ] 90 tests.
```

** 2.6	Dumper-APPモジュール結合テスト

$ bash adx.sh --launch_file test/DumperTest/test_dumper.launch.hjson --online_mode --quit_time 60

正しく動かない。/adx/srcでのビルドは正しくは $ make TEST_DUMPER=1 WOCUDA=1

その後で

$ bash adx.sh --launch_file test/DumperTest/test_dumper.launch.hjson --offline_mode --quit_replay_complete 

$ bash test/DumperTest/iotest_log_checker/test_dumper_log_checker_run.sh log_20181003_031934 log_20181003_035317

```
$ bash test/DumperTest/iotest_log_checker/test_dumper_log_checker_run.sh log_20181003_031934 log_20181003_035317
----
log_20181003_031934/TestAppDumper_TestDataSource.log
log_20181003_035317/TestAppDumper_TestDataSink.log
check OK.
----
```

OK

** 2.7	Dumperベンチマークテスト

testデータは(samba) \\\\nxtmc.fixstars.com\\sdb1\\ecu-fw\\testdata
から取得できる。

$ ../../build/PC/gtest/dumper/test.exe --gtest_also_run_disabled_tests --gtest_filter=Benchmark*

```
$ ../../build/PC/gtest/dumper/test.exe --gtest_also_run_disabled_tests --gtest_filter=Benchmark*
Note: Google Test filter = Benchmark*
[==========] Running 4 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from Benchmark_DumpWriterTest
[ RUN      ] Benchmark_DumpWriterTest.DISABLED_Fluency
../../test/DumperTest/TestData/aSvJ6jTY6I4_02490_(2736x2192_rgb24).raw
type:0 level:0 iteration:300 threads:3 queue:10  416stuck  total 19.5054fps 46.141sec 334.684MiB/s 100%
type:0 level:1 iteration:300 threads:3 queue:10  0stuck  total 27.7915fps 32.384sec 144.785MiB/s 30.3621%
[       OK ] Benchmark_DumpWriterTest.DISABLED_Fluency (79306 ms)
[ RUN      ] Benchmark_DumpWriterTest.DISABLED_Zstandard
../../test/DumperTest/TestData/aSvJ6jTY6I4_02490_(2736x2192_rgb24).raw
type:0 level:0 iteration:300 threads:3 queue:10  total 31.452fps 28.615sec 539.67MiB/s 100%
type:0 level:1 iteration:300 threads:3 queue:10  total 43.1096fps 20.877sec 224.588MiB/s 30.3621%
[       OK ] Benchmark_DumpWriterTest.DISABLED_Zstandard (50451 ms)
[----------] 2 tests from Benchmark_DumpWriterTest (129757 ms total)

[----------] 2 tests from Benchmark_DumpReaderTest
[ RUN      ] Benchmark_DumpReaderTest.DISABLED_Fluency
../../test/DumperTest/TestData/aSvJ6jTY6I4_02490_(2736x2192_rgb24).raw
type:0 level:0 iteration:300 threads:3 queue:10  0stuck  total 29.984fps 30.016sec 514.481MiB/s 100%
type:0 level:1 iteration:300 threads:3 queue:10  0stuck  total 29.978fps 30.022sec 156.176MiB/s 30.3621%
[       OK ] Benchmark_DumpReaderTest.DISABLED_Fluency (110810 ms)
[ RUN      ] Benchmark_DumpReaderTest.DISABLED_Zstandard
../../test/DumperTest/TestData/aSvJ6jTY6I4_02490_(2736x2192_rgb24).raw
type:0 level:0 iteration:300 threads:3 queue:10  total 48.7435fps 18.464sec 836.366MiB/s 100%
type:0 level:1 iteration:300 threads:3 queue:10  total 70.1754fps 12.825sec 365.592MiB/s 30.3621%
[       OK ] Benchmark_DumpReaderTest.DISABLED_Zstandard (80881 ms)
[----------] 2 tests from Benchmark_DumpReaderTest (191691 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 2 test cases ran. (321448 ms total)
[  PASSED  ] 4 tests.

```

*
" . 43254) ((marker* . 43254) . 1569) ((marker* . 43254) . 1569) ((marker* . 43254) . 1569) ((marker* . 43254) . 1569) ((marker . 43254) . -14260) ((marker* . 43254) . 1569) ((marker* . 43254) . 1569) ((marker . 43254) . -14260) ((marker* . 43254) . 1569) ((marker* . 43254) . 1569) ((marker . 43254) . -14260) ((marker* . 43254) . 1569) ((marker* . 43254) . 1569) ((marker . 43254) . -14260) ((marker . 43254) . -14260) ((marker . 43254) . -14778) ((marker . 10) . -15578) ((marker . 43254) . -16347) ((marker . 43254) . -16347) ((marker . 43254) . -16347) ((marker) . -16347) 59601 nil ("
*10/1

** その１

- DOCERではなくenp0s3相手にIPアドレスを指定

```
c:\\auto_drive_system\\src\\2020_highway\\scripts\\iotest_log_checker>iotest_log_checker_run.bat c:\\auto_drive_system\\src\\work\\log\\20181001_123431_logs
c:\\auto_drive_system\\src\\work\\log\\20181001_123431_logs\\\\20181001_123431_pu_appfw_test_send_0_outerr.log
c:\\auto_drive_system\\src\\work\\log\\20181001_123431_logs\\\\20181001_123431_pu_text_recv_0_outerr.log
dataid:39 check OK.
dataid:40 check OK.
dataid:41 check OK.
dataid:42 check OK.
dataid:43 check OK.
dataid:44 check OK.
dataid:45 check OK.
dataid:46 check OK.
dataid:47 check OK.
dataid:48 check OK.
dataid:49 check OK.
```
とOKが出た。

-その前の時になぜうまく出なかったのかは疑問。

-逆の｜ADX→ADSは手順ミスで２回めに成功。

**その２

-20tmは持ってきてビルド
--dockerイメージも新しく持ってきた
---実際実行してみるとVIN fileIO init errorがでまくっている

-adxはその１そのままだったが一応もう一度持ってきてコンパイル
--dockerイメージはそのまま
---実際実行してみるとhjsonの解釈で配信モジュールが存在しませんばかりで起動せず。
" . 1) ((marker . 1) . -867) ((marker . 10) . -658) ((marker . 43254) . -867) ((marker . 43254) . -867) ((marker) . -867) 868 (t 23476 18663 275361 458000) nil (60467 . 60468) 44129 nil ("*" . -60467) ((marker . 43254) . -1) ((marker . 43254) . -1) 60468 nil (60466 . 60468) nil (60465 . 60466) nil (nil rear-nonsticky nil 60459 . 60460) (nil fontified nil 58284 . 60460) (58284 . 60460) nil (58284 . 58285) nil (58287 . 58288) nil (58284 . 58287) nil (58283 . 58284) nil (58280 . 58283) nil (58279 . 58280) nil (690 . 691) nil ("
" . 664) ((marker . 43254) . -1) nil (664 . 665) nil (873 . 874) nil (15 . 16) (t 23476 16716 899361 458000) nil (58275 . 58276) (nil rear-nonsticky nil 58274 . 58275) (nil fontified nil 58181 . 58275) (58181 . 58275) nil (58179 . 58181) nil ("$" . -58179) 58180 nil (58179 . 58180) (t 23476 16620 355361 458000) nil (58178 . 58179) (t 23476 16554 807361 458000) nil (58177 . 58178) nil (nil rear-nonsticky nil 58108 . 58109) (nil fontified nil 58090 . 58109) (58090 . 58109) nil ("2.8	Dumperベンチマーク組み合わせテスト" . 58090) nil (nil rear-nonsticky nil 58113 . 58114) (nil fontified nil 58090 . 58114) (58090 . 58114) nil (58150 . 58158) nil (nil rear-nonsticky nil 58149 . 58150) (nil fontified nil 58100 . 58150) (58100 . 58150) nil (58094 . 58100) nil (58092 . 58094) nil (58090 . 58092) nil (58087 . 58090) nil ("/" . -58087) 58088 nil (58087 . 58088) nil (58085 . 58087) nil (58083 . 58085) nil ("t" . -58083) ("u" . -58084) ("g" . -58085) ("i" . -58086) 58087 nil (58083 . 58087) nil (58082 . 58083) nil (57841 . 57842) nil ("\\" . -57841) 57842 nil (57841 . 57842) nil ("&" . -57841) 57842 nil (57841 . 57842) nil ("
" . 58077) nil (nil rear-nonsticky nil 58076 . 58077) (nil fontified nil 57841 . 58077) (57841 . 58077) (t 23476 16110 615361 458000) nil (57841 . 57842) nil (57844 . 57845) nil (57841 . 57844) nil (57840 . 57841) nil (57837 . 57840) nil (57836 . 57837) (t 23476 16044 687361 458000) nil (nil rear-nonsticky nil 57834 . 57835) (nil fontified nil 57816 . 57835) (57816 . 57835) nil (" " . -57816) 57817 nil (57815 . 57816) (t 23476 16011 871361 458000) nil (57815 . 57816) nil (nil rear-nonsticky nil 57814 . 57815) (nil fontified nil 57796 . 57815) (57796 . 57815) (t 23476 15996 999361 458000) nil (57795 . 57797) nil (nil rear-nonsticky nil 57794 . 57795) (nil fontified nil 57724 . 57795) (57724 . 57795) nil (57723 . 57724) nil (57722 . 57723) (t 23476 15646 759361 458000) nil (57721 . 57722) 57614 nil (nil fontified nil 57719 . 57720) (nil fontified nil 57614 . 57719) (57614 . 57720) nil ("$ bash adx.sh --launch_file test/DumperTest/test_dumper.launch.hjson --offline_mode --quit_replay_complete" . -57614) 57720 nil (nil rear-nonsticky nil 57719 . 57720) (nil fontified nil 57614 . 57720) (57614 . 57720) nil (57612 . 57614) nil (57608 . 57612) nil ("s" . -57608) ("o" . -57609) ("n" . -57610) ("o" . -57611) 57612 nil (57608 . 57612) nil (57606 . 57608) nil (57598 . 57606) nil (57587 . 57598) nil ("t" . -57587) 57588 nil (57587 . 57588) nil (57583 . 57587) nil (57578 . 57579) nil (57572 . 57583) nil ("t" . -57572) ("a" . -57573) 57574 nil (57566 . 57574) nil (57558 . 57566) nil ("a" . -57558) ("d" . -57559) ("x" . -57560) 57561 nil (57550 . 57561) nil ("q" . 44118) nil ("r" . 31589) nil (31516 . 31517) nil ("```


** 2.4	Dumper共通処理単体テス
" . -36526) 36554 nil (36553 . 36555) ("ト" . 36553) nil (44153 . 44154) nil (44188 . 44189) nil ("u" . -57576) 57577 nil ("m" . -57577) ("a" . -57578) ("
" . -57579) 57580 nil (57576 . 57579) nil (57575 . 57576) nil (57574 . 57575) (t 23476 11044 36000 0) nil (57574 . 57575) (nil rear-nonsticky nil 57573 . 57574) (nil fontified nil 57477 . 57574) (57477 . 57574) nil (57475 . 57477) nil (nil rear-nonsticky nil 57474 . 57475) (nil fontified nil 57451 . 57475) (57451 . 57475) nil (57449 . 57450) nil (57449 . 57450) nil ("2" . -57449) 57450 nil (57448 . 57450) nil (":" . -57448) ("2" . -57449) 57450 nil (57448 . 57450) nil (57447 . 57448) nil ("
" . 57443) nil (44145 . 44146) (t 23476 7115 124000 0) nil (nil rear-nonsticky nil 57441 . 57442) (nil fontified nil 44265 . 57442) (44265 . 57442) (t 23476 7094 504000 0) nil (44265 . 44266) nil (44268 . 44269) nil (44265 . 44268) nil (44264 . 44265) nil (44261 . 44264) nil (44260 . 44261) (t 23476 7028 440000 0) nil ("
" . -44260) 44261 nil (nil rear-nonsticky nil 44260 . 44261) (nil fontified nil 44189 . 44261) (44189 . 44261) nil (44188 . 44189) nil (nil rear-nonsticky nil 44186 . 44187) (nil fontified nil 44156 . 44187) (44156 . 44187) nil (44153 . 44156) nil (44146 . 44147) nil (44150 . 44152) nil (44145 . 44150) nil (44143 . 44145) (t 23475 16774 51374 564000) nil (36618 . 36619) (t 23475 15246 967374 564000) nil (nil rear-nonsticky nil 44137 . 44138) (nil fontified nil 36622 . 44138) (36622 . 44138) (t 23475 15008 791374 564000) nil (36622 . 36623) nil (36625 . 36626) nil (36622 . 36625) nil (36621 . 36622) nil (36618 . 36621) nil (36617 . 36618) nil (nil rear-nonsticky nil 36616 . 36617) (nil fontified nil 36556 . 36617) (36556 . 36617) nil (36554 . 36556) nil (nil rear-nonsticky nil 36553 . 36554) (nil fontified nil 36535 . 36554) (36535 . 36554) nil (36532 . 36535) nil (36530 . 36532) (t 23475 14621 375374 564000) nil ("
" . 36526) nil (nil rear-nonsticky nil 36525 . 36526) (nil fontified nil 31588 . 36526) (31588 . 36526) (t 23475 14592 907374 564000) nil ("$" . -31588) (" " . -31589) 31590 nil ("." . -31590) ("." . -31591) ("/" . -31592) ("." . -31593) ("." . -31594) ("/" . -31595) ("b" . -31596) ("u" . -31597) ("i" . -31598) ("l" . -31599) ("d" . -31600) ("/" . -31601) ("P" . -31602) ("C" . -31603) ("/" . -31604) ("g" . -31605) ("t" . -31606) ("e" . -31607) ("s" . -31608) ("t" . -31609) ("/" . -31610) 31611 nil ("dumper/test.exe --gtest_filter=DumpWriter*
Note: Google Test filter = DumpWriter*
[==========] Running 50 tests from 6 test cases.
[----------] Global test environment set-up.
[----------] 6 tests from DumpWriter_HeaderCreatorTest
[ RUN      ] DumpWriter_HeaderCreatorTest.Accessors
[       OK ] DumpWriter_HeaderCreatorTest.Accessors (0 ms)
[ RUN      ] DumpWriter_HeaderCreatorTest.BaseName
[       OK ] DumpWriter_HeaderCreatorTest.BaseName (0 ms)
[ RUN      ] DumpWriter_HeaderCreatorTest.NoSlashContainedBaseName
[       OK ] DumpWriter_HeaderCreatorTest.NoSlashContainedBaseName (0 ms)
[ RUN      ] DumpWriter_HeaderCreatorTest.FileHeader
[       OK ] DumpWriter_HeaderCreatorTest.FileHeader (0 ms)
[ RUN      ] DumpWriter_HeaderCreatorTest.NotGerneratedUnnecessaryHeader
[       OK ] DumpWriter_HeaderCreatorTest.NotGerneratedUnnecessaryHeader (0 ms)
[ RUN      ] DumpWriter_HeaderCreatorTest.FrameHeader
[       OK ] DumpWriter_HeaderCreatorTest.FrameHeader (0 ms)
[----------] 6 tests from DumpWriter_HeaderCreatorTest (0 ms total)

[----------] 3 tests from DumpWriter_ChannelTest
[ RUN      ] DumpWriter_ChannelTest.Queueing
[       OK ] DumpWriter_ChannelTest.Queueing (0 ms)
[ RUN      ] DumpWriter_ChannelTest.Cancel
[       OK ] DumpWriter_ChannelTest.Cancel (0 ms)
[ RUN      ] DumpWriter_ChannelTest.Fail
[       OK ] DumpWriter_ChannelTest.Fail (0 ms)
[----------] 3 tests from DumpWriter_ChannelTest (0 ms total)

[----------] 5 tests from DumpWriter_FileWriterTest
[ RUN      ] DumpWriter_FileWriterTest.BadCompressType
[       OK ] DumpWriter_FileWriterTest.BadCompressType (0 ms)
[ RUN      ] DumpWriter_FileWriterTest.BadFactory
[       OK ] DumpWriter_FileWriterTest.BadFactory (1 ms)
[ RUN      ] DumpWriter_FileWriterTest.BadCompressor
[       OK ] DumpWriter_FileWriterTest.BadCompressor (0 ms)
[ RUN      ] DumpWriter_FileWriterTest.SingleSink
[       OK ] DumpWriter_FileWriterTest.SingleSink (1 ms)
[ RUN      ] DumpWriter_FileWriterTest.MultiSink
[       OK ] DumpWriter_FileWriterTest.MultiSink (1 ms)
[----------] 5 tests from DumpWriter_FileWriterTest (3 ms total)

[----------] 22 tests from DumpWriter_DumpWriterTest
[ RUN      ] DumpWriter_DumpWriterTest.Initialize
[       OK ] DumpWriter_DumpWriterTest.Initialize (4 ms)
[ RUN      ] DumpWriter_DumpWriterTest.NullWriter
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] DumpWriter_Initialize: null pointer argument
[       OK ] DumpWriter_DumpWriterTest.NullWriter (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.NullOptions
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] DumpWriter_Initialize: null pointer argument
[       OK ] DumpWriter_DumpWriterTest.NullOptions (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.NullDataInfo
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] data_info must be non-null value
[       OK ] DumpWriter_DumpWriterTest.NullDataInfo (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.NullBaseName
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] base_name must be non-null value
[       OK ] DumpWriter_DumpWriterTest.NullBaseName (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.UnknownCompressType
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] unsupported compress type: 100
[       OK ] DumpWriter_DumpWriterTest.UnknownCompressType (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.BadCompressLevel
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] unsupported compress level: 9999
[       OK ] DumpWriter_DumpWriterTest.BadCompressLevel (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.ZeroMaxFileSize
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] max_file_size_mb must be non-zero value
[       OK ] DumpWriter_DumpWriterTest.ZeroMaxFileSize (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.ZeroRawDataSize
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] raw_data_size must be non-zero value
[       OK ] DumpWriter_DumpWriterTest.ZeroRawDataSize (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.ZeroSerializedDataSize
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] serialized_data_size must be non-zero value
[       OK ] DumpWriter_DumpWriterTest.ZeroSerializedDataSize (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.ZeroQueueDepth
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] queue_depth must be non-zero value
[       OK ] DumpWriter_DumpWriterTest.ZeroQueueDepth (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.NullStartDatetime
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] start_datetime must be non-null value
[       OK ] DumpWriter_DumpWriterTest.NullStartDatetime (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.DumpNullSerializePtr
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] serialize_func_ptr must be non-null value
[       OK ] DumpWriter_DumpWriterTest.DumpNullSerializePtr (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.DumpNullApp
[       OK ] DumpWriter_DumpWriterTest.DumpNullApp (2 ms)
[ RUN      ] DumpWriter_DumpWriterTest.DumpNullModule
[       OK ] DumpWriter_DumpWriterTest.DumpNullModule (2 ms)
[ RUN      ] DumpWriter_DumpWriterTest.DumpNullMessage
[       OK ] DumpWriter_DumpWriterTest.DumpNullMessage (2 ms)
[ RUN      ] DumpWriter_DumpWriterTest.DumpNullWriter
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] DumpWriter_Dump: null pointer argument
[       OK ] DumpWriter_DumpWriterTest.DumpNullWriter (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.DumpNullDataPtr
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] DumpWriter_Dump: null pointer argument
[       OK ] DumpWriter_DumpWriterTest.DumpNullDataPtr (2 ms)
[ RUN      ] DumpWriter_DumpWriterTest.IsFull
[       OK ] DumpWriter_DumpWriterTest.IsFull (1 ms)
[ RUN      ] DumpWriter_DumpWriterTest.IsFullNullWriter
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] DumpWriter_IsFull: null pointer argument
[       OK ] DumpWriter_DumpWriterTest.IsFullNullWriter (0 ms)
[ RUN      ] DumpWriter_DumpWriterTest.IsFullNullDest
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] DumpWriter_IsFull: null pointer argument
[       OK ] DumpWriter_DumpWriterTest.IsFullNullDest (1 ms)
[ RUN      ] DumpWriter_DumpWriterTest.WriteOnlyFileHeader
[       OK ] DumpWriter_DumpWriterTest.WriteOnlyFileHeader (2 ms)
[----------] 22 tests from DumpWriter_DumpWriterTest (17 ms total)

[----------] 8 tests from DumpWriter_WorkerTest/DumpWriter_WorkerTest
[ RUN      ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.NormalWorker/0
[       OK ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.NormalWorker/0 (32 ms)
[ RUN      ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.NormalWorker/1
[       OK ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.NormalWorker/1 (19 ms)
[ RUN      ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.NormalWorker/2
[       OK ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.NormalWorker/2 (6 ms)
[ RUN      ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.NormalWorker/3
[       OK ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.NormalWorker/3 (2 ms)
[ RUN      ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.AbnormalWorker/0
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] terminate write thread
[       OK ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.AbnormalWorker/0 (7 ms)
[ RUN      ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.AbnormalWorker/1
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] terminate write thread
[       OK ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.AbnormalWorker/1 (2 ms)
[ RUN      ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.AbnormalWorker/2
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] terminate write thread
[       OK ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.AbnormalWorker/2 (3 ms)
[ RUN      ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.AbnormalWorker/3
2018-10-02T09:14:49+0000 18446744073709551615 ERR [UNKNOWN] terminate write thread
[       OK ] DumpWriter_WorkerTest/DumpWriter_WorkerTest.AbnormalWorker/3 (1 ms)
[----------] 8 tests from DumpWriter_WorkerTest/DumpWriter_WorkerTest (72 ms total)

[----------] 6 tests from DumpWriter_Checksum/DumpWriterChecksumTest
[ RUN      ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFileHeaderChecksum/0
[       OK ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFileHeaderChecksum/0 (0 ms)
[ RUN      ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFileHeaderChecksum/1
[       OK ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFileHeaderChecksum/1 (0 ms)
[ RUN      ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFrameDelimiter/0
[       OK ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFrameDelimiter/0 (0 ms)
[ RUN      ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFrameDelimiter/1
[       OK ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFrameDelimiter/1 (0 ms)
[ RUN      ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFrameChecksum/0
[       OK ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFrameChecksum/0 (0 ms)
[ RUN      ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFrameChecksum/1
[       OK ] DumpWriter_Checksum/DumpWriterChecksumTest.FileSinkFrameChecksum/1 (0 ms)
[----------] 6 tests from DumpWriter_Checksum/DumpWriterChecksumTest (0 ms total)

[----------] Global test environment tear-down
[==========] 50 tests from 6 test cases ran. (95 ms total)
[  EPASSED  ] 50 tests." . 31611) nil (40956 . 40957) (t 23475 14119 835374 564000) nil ("
" . 40976) nil (nil rear-nonsticky nil 40975 . 40976) (nil fontified nil 31588 . 40976) (31588 . 40976) nil (31588 . 31589) nil (31591 . 31592) nil (31588 . 31591) nil (31587 . 31588) nil (31584 . 31587) nil (31583 . 31584) (t 23475 14070 723374 564000) nil (31582 . 31583) 31541 nil (nil rear-nonsticky nil 31515 . 31516) (nil fontified nil 31491 . 31516) (31491 . 31516) nil (31488 . 31491) nil (nil rear-nonsticky nil 31553 . 31554) (nil fontified nil 31489 . 31554) (31489 . 31554) nil (31487 . 31489) nil (21994 . 21995) nil (2485 . 2486) nil (nil rear-nonsticky nil 2484 . 2485) (nil fontified nil 2461 . 2485) (2461 . 2485) nil (2459 . 2461) nil (21993 . 21994) nil (21967 . 21968) nil (21966 . 21967) nil (nil rear-nonsticky nil 21989 . 21990) (nil fontified nil 21966 . 21990) (21966 . 21990) (t 23475 13024 883374 564000) nil ("
" . 31428) nil (nil rear-nonsticky nil 31427 . 31428) (nil fontified nil 22038 . 31428) (22038 . 31428) (t 23475 12936 839374 564000) nil (22042 . 22043) 22039 nil (22038 . 22039) nil (22033 . 22034) nil (22037 . 22040) nil (22036 . 22037) nil (22033 . 22036) nil ("2" . -22033) 22034 nil (22033 . 22034) (t 23475 11013 199374 564000) nil (22032 . 22033) (nil rear-nonsticky nil 22031 . 22032) (nil fontified nil 21967 . 22032) (21967 . 22032) (t 23475 10986 987374 564000) nil (21965 . 21967) nil (21953 . 21965) nil (21938 . 21953) nil (21937 . 21938) (t 23475 8849 263374 564000) nil (nil rear-nonsticky nil 21931 . 21932) (nil fontified nil 2530 . 21932) (2530 . 21932) (t 23475 8820 799374 564000) nil (2534 . 2535) (2529 . 2530) nil (2530 . 2533) nil (2529 . 2530) nil (2526 . 2529) (t 23475 8785 995374 564000) nil (2525 . 2526) (nil rear-nonsticky nil 2524 . 2525) (nil fontified nil 2460 . 2525) (2460 . 2525) nil (2458 . 2460) nil (2455 . 2458) nil ("t" . -2455) ("e" . -2456) ("s" . -2457) ("u" . -2458) ("t" . -2459) ("o" . -2460) (" " . -2461) ("
" . -2462) 2463 nil (2462 . 2463) nil (2455 . 2462) nil ("-" . -2455) 2456 nil (2454 . 2456) nil (2452 . 2454) nil (2444 . 2452) nil (2443 . 2444) (t 23475 8240 611374 564000) nil (2442 . 2443) (2430 . 2432) nil (2430 . 2440) nil (2428 . 2430) nil (2418 . 2428) nil ("c" . -2418) ("d" . -2419) (" " . -2420) 2421 nil (2417 . 2421) nil ("#" . -2417) ("c" . -2418) ("d" . -2419) (" " . -2420) 2421 nil (2417 . 2421) (t 23475 8209 379374 564000) nil (2415 . 2417) nil (" " . -2415) 2416 nil (" " . 2407) nil (2406 . 2407) nil (" " . 2388) ("e" . 2388) ("k" . 2388) ("a" . 2388) ("m" . 2388) (" " . 2388) ("$" . 2388) nil (nil rear-nonsticky nil 2421 . 2422) (nil fontified nil 2395 . 2422) (2395 . 2422) nil (2388 . 2395) nil (2387 . 2388) nil (2381 . 2387) nil (2378 . 2381) nil (2375 . 2376) nil (2374 . 2378) (t 23475 6352 687374 564000) nil (2316 . 2317) nil (nil rear-nonsticky nil 2371 . 2372) (nil fontified nil 2286 . 2372) (2286 . 2372) (t 23475 6325 43374 564000) nil (2274 . 2287) nil ("-" . -2274) ("b" . -2275) 2276 nil (2275 . 2276) nil ("e" . -2275) 2276 nil (2275 . 2276) nil ("0" . -2275) 2276 nil (2269 . 2276) nil ("g" . -2269) ("f" . -2270) ("i" . -2271) ("t" . -2272) 2273 nil (2268 . 2273) nil (2267 . 2268) nil (2262 . 2267) nil (2258 . 2262) nil ("f" . -2258) ("g" . -2259) 2260 nil (2259 . 2260) nil ("i" . -2259) ("t" . -2260) 2261 nil (2258 . 2261) nil ("f" . -2258) ("g" . -2259) ("\\" . -2260) 2261 nil (2260 . 2261) nil ("i" . -2260) 2261 nil (2256 . 2261) nil (2182 . 2183) nil (nil rear-nonsticky nil 2254 . 2255) (nil fontified nil 2182 . 2255) (2182 . 2255) nil (2181 . 2182) (t 23475 4312 303374 564000) nil (2180 . 2181) nil (2175 . 2180) nil ("-" . -2175) 2176 nil (2174 . 2176) nil (2172 . 2174) nil (2170 . 2172) nil ("う" . -2170) 2171 nil (2163 . 2171) nil (2142 . 2163) nil (2129 . 2142) nil (2128 . 2129) nil (2120 . 2128) nil (" " . -2120) (" " . -2121) (" " . -2122) (" " . -2123) ("d" . -2124) ("o" . -2125) ("o" . -2126) ("u" . -2127) 2128 nil (2125 . 2128) nil (2120 . 2125) nil ("　" . -2120) ("　" . -2121) 2122 nil (2120 . 2122) nil (2119 . 2120) nil (2103 . 2119) nil (2094 . 2103) nil ("?" . -2094) 2095 nil (2084 . 2095) nil (2072 . 2079) nil (2062 . 2072) nil ("管" . -2062) ("理" . -2063) ("用" . -2064) 2065 nil (2059 . 2065) nil (2056 . 2059) nil (2057 . 2061) (t 23474 57579 77000 0) nil (nil rear-nonsticky nil 2055 . 2056) (nil fontified nil 2027 . 2056) (2027 . 2056) nil (2026 . 2027) nil (nil rear-nonsticky nil 2025 . 2026) (nil fontified nil 2008 . 2026) (2008 . 2026) nil (2005 . 2008) nil (2004 . 2005) nil (1998 . 1999) nil ("と" . -1998) 1999 nil ("を" . 1999) ("m" . 1999) ("e" . 1999) ("t" . 1999) ("s" . 1999) ("y" . 1999) ("s" . 1999) ("_" . 1999) ("e" . 1999) ("v" . 1999) ("i" . 1999) ("r" . 1999) ("d" . 1999) ("_" . 1999) ("o" . 1999) ("t" . 1999) ("u" . 1999) ("a" . 1999) (t 23474 56976 105000 0) nil (2022 . 2023) nil (2016 . 2022) nil (2009 . 2016) nil ("?" . -2009) 2010 nil (2005 . 2010) nil ("p" . -2005) 2006 nil (2003 . 2006) nil (1987 . 2003) nil ("t" . -1987) ("u" . -1988) 1989 nil (1987 . 1989) (t 23474 55427 721000 0) nil (1985 . 1987) nil (1983 . 1985) nil (1979 . 1983) nil ("s" . -1979) ("o" . -1980) ("n" . -1981) ("o" . -1982) 1983 nil (1978 . 1983) nil (":" . -1978) 1979 nil (1978 . 1979) (t 23474 54611 353000 0) nil (1976 . 1977) nil (1967 . 1976) nil (1962 . 1967) nil ("?" . -1962) ("f" . -1963) ("i" . -1964) 1965 nil (1958 . 1965) nil ("n" . -1958) ("c" . -1959) ("h" . -1960) 1961 nil (1954 . 1961) nil (1953 . 1954) nil ("." . -1953) ("." . -1954) ("." . -1955) 1956 nil (1953 . 1956) (t 23474 54566 789000 0) nil (nil rear-nonsticky nil 1952 . 1953) (nil fontified nil 1890 . 1953) (1890 . 1953) nil (1889 . 1890) (t 23474 54538 273000 0) nil (1887 . 1889) nil (1806 . 1807) nil (nil rear-nonsticky nil 1886 . 1887) (nil fontified nil 1806 . 1887) (1806 . 1887) (t 23474 54513 461000 0) nil (1805 . 1806) nil (1788 . 1805) nil (1787 . 1788) nil (1779 . 1780) nil (1779 . 1786) nil ("k" . -1779) ("i" . -1780) ("n" . -1781) ("o" . -1782) 1783 nil (1779 . 1783) nil (1778 . 1779) (t 23474 53391 941000 0) nil (nil fontified t 1114 . 1116) ("+ " . 1114) (1116 . 1118) (nil fontified t 1235 . 1237) ("+ " . 1235) (1237 . 1239) (nil fontified t 1268 . 1270) ("+ " . 1268) (1270 . 1272) 1183 nil (nil fontified t 1114 . 1116) ("* " . 1114) (1116 . 1118) (nil fontified t 1235 . 1237) ("* " . 1235) (1237 . 1239) (nil fontified t 1268 . 1270) ("* " . 1268) (1270 . 1272) 1183 nil (nil fontified t 1114 . 1116) ("1. " . 1114) (1117 . 1119) (1185 . 1189) ("     " . -1185) (nil fontified t 1237 . 1239) ("2. " . 1237) (1240 . 1242) (nil fontified t 1271 . 1273) ("3. " . 1271) (1274 . 1276) 1184 nil (nil fontified t 1114 . 1117) ("1) " . 1114) (1117 . 1120) (nil fontified t 1237 . 1240) ("2) " . 1237) (1240 . 1243) (nil fontified t 1271 . 1274) ("3) " . 1271) (1274 . 1277) 1184 nil (nil fontified t 1115 . 1117) ("- " . 1114) (1116 . 1119) (1184 . 1189) ("    " . -1184) (nil fontified t 1236 . 1238) ("- " . 1235) (1237 . 1240) (nil fontified t 1269 . 1271) ("- " . 1268) (1270 . 1273) 1183 nil (nil fontified t 1114 . 1116) ("+ " . 1114) (1116 . 1118) (nil fontified t 1235 . 1237) ("+ " . 1235) (1237 . 1239) (nil fontified t 1268 . 1270) ("+ " . 1268) (1270 . 1272) 1183 nil (nil fontified t 1114 . 1116) ("* " . 1114) (1116 . 1118) (nil fontified t 1235 . 1237) ("* " . 1235) (1237 . 1239) (nil fontified t 1268 . 1270) ("* " . 1268) (1270 . 1272) 1183 nil (nil fontified t 1114 . 1116) ("1. " . 1114) (1117 . 1119) (1185 . 1189) ("     " . -1185) (nil fontified t 1237 . 1239) ("2. " . 1237) (1240 . 1242) (nil fontified t 1271 . 1273) ("3. " . 1271) (1274 . 1276) 1184 nil (nil fontified t 1114 . 1117) ("1) " . 1114) (1117 . 1120) (nil fontified t 1237 . 1240) ("2) " . 1237) (1240 . 1243) (nil fontified t 1271 . 1274) ("3) " . 1271) (1274 . 1277) 1184 nil (nil fontified t 1115 . 1117) ("- " . 1114) (1116 . 1119) (1184 . 1189) ("    " . -1184) (nil fontified t 1236 . 1238) ("- " . 1235) (1237 . 1240) (nil fontified t 1269 . 1271) ("- " . 1268) (1270 . 1273) 1183 nil (nil fontified t 1114 . 1116) ("+ " . 1114) (1116 . 1118) (nil fontified t 1235 . 1237) ("+ " . 1235) (1237 . 1239) (nil fontified t 1268 . 1270) ("+ " . 1268) (1270 . 1272) 1183 nil (nil fontified t 1114 . 1116) ("* " . 1114) (1116 . 1118) (nil fontified t 1235 . 1237) ("* " . 1235) (1237 . 1239) (nil fontified t 1268 . 1270) ("* " . 1268) (1270 . 1272) 1183 nil (nil fontified t 1114 . 1116) ("1. " . 1114) (1117 . 1119) (1185 . 1189) ("     " . -1185) (nil fontified t 1237 . 1239) ("2. " . 1237) (1240 . 1242) (nil fontified t 1271 . 1273) ("3. " . 1271) (1274 . 1276) 1184 nil (nil fontified t 1114 . 1117) ("1) " . 1114) (1117 . 1120) (nil fontified t 1237 . 1240) ("2) " . 1237) (1240 . 1243) (nil fontified t 1271 . 1274) ("3) " . 1271) (1274 . 1277) 1184 nil (nil fontified t 1115 . 1117) ("- " . 1114) (1116 . 1119) (1184 . 1189) ("    " . -1184) (nil fontified t 1236 . 1238) ("- " . 1235) (1237 . 1240) (nil fontified t 1269 . 1271) ("- " . 1268) (1270 . 1273) 1183 nil (nil fontified t 1114 . 1116) ("+ " . 1114) (1116 . 1118) (nil fontified t 1235 . 1237) ("+ " . 1235) (1237 . 1239) (nil fontified t 1268 . 1270) ("+ " . 1268) (1270 . 1272) 1183 nil ("* " . 1114) (1116 . 1118) ("* " . 1235) (1237 . 1239) ("* " . 1268) (t 23474 53315 441000 0) (1270 . 1272) 1183 (t 23474 53315 441000 0) nil (1678 . 1679) nil (1541 . 1542) nil ("
" . -1315) 1316 nil (1315 . 1318) ("実行" . 1315) nil (" " . -1315) 1316 nil (1315 . 1316) nil ("
" . -1110) 1111 nil (1110 . 1112) ("行" . 1110) nil ("
" . -1308) 1309 nil (1308 . 1309) nil ("
" . -1101) 1102 nil (1102 . 1103) nil (931 . 932) nil (nil rear-nonsticky nil 1774 . 1775) (nil fontified nil 925 . 1775) (925 . 1775) (t 23474 53218 569000 0) nil (923 . 925) nil (nil rear-nonsticky nil 922 . 923) (nil fontified nil 874 . 923) (874 . 923) nil ("R" . -874) ("E" . -875) 876 nil (874 . 876) nil (872 . 874) nil (867 . 872) nil ("1" . -867) ("0" . -868) 869 nil (867 . 869) nil (866 . 867) (t 23473 59348 688000 0) nil (856 . 865) nil (842 . 856) (t 23473 59311 72000 0) nil (824 . 842) nil (821 . 824) nil ("
" . 769) nil (761 . 768) nil (755 . 761) nil ("E" . -755) ("R" . -756) ("O" . -757) 758 nil (740 . 758) nil (739 . 740) nil ("f" . -739) ("i" . -740) ("l" . -741) ("e" . -742) 743 nil (730 . 743) nil ("b" . -730) ("i" . -731) 732 nil (730 . 732) nil (727 . 730) nil (727 . 730) nil (778 . 779) (t 23473 54258 396000 0) nil (777 . 778) nil (762 . 777) nil (760 . 762) nil (713 . 726) nil (705 . 713) nil (705 . 706) nil (737 . 738) nil (717 . 737) nil (706 . 717) nil ("-" . -706) 707 nil (706 . 707) nil (705 . 706) nil (704 . 705) nil (701 . 704) nil (695 . 701) nil (690 . 691) nil (" " . -690) (" " . -691) 692 nil (690 . 692) nil (690 . 694) (t 23473 51244 416000 0) nil (670 . 682) nil (669 . 670) nil ("も" . -669) 670 nil (665 . 670) nil (658 . 665) nil (657 . 659) (t 23473 40592 590077 599000) nil (663 . 664) nil (8 . 9) nil (659 . 662) nil (658 . 659) nil (11 . 14) nil ("s" . -11) ("o" . -12) ("n" . -13) ("o" . -14) 15 nil (11 . 15) nil ("s" . -11) ("i" . -12) 13 nil (8 . 13) nil (8 . 9) nil (650 . 651) nil (648 . 650) nil (625 . 626) nil (646 . 647) nil (625 . 646) nil (623 . 625) nil (619 . 623) nil (616 . 619) nil ("t" . -616) ("o" . -617) ("
" . -618) 619 nil (618 . 619) nil (616 . 618) nil ("
" . 612) nil ("続行するには何かキーを押してください . . ." . 612) nil (nil rear-nonsticky nil 635 . 636) (nil fontified nil 43 . 636) (43 . 636) nil (43 . 44) nil (46 . 47) nil (43 . 46) nil (42 . 43) nil (39 . 42) nil (37 . 39) nil (28 . 37) nil ("D" . -28) 29 nil (25 . 29) nil (10 . 25) nil ("K" . -10) ("O" . -11) 12 nil (10 . 12) nil (8 . 10) nil (7 . 8) nil (2 . 7) nil ("." . -2) ("/" . -3) 4 nil (2 . 4) nil ("1" . -2) ("0" . -3) ("/" . -4) 5 nil (4 . 5) nil ("." . -4) 5 nil (2 . 5) (t 23458 63935 243000 0) nil ("これからやること" . 1) nil (9 . 10) nil (1 . 9) (t . -1)))
